//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.NewProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Order product.
    /// </summary>
    // *** Start programmer edit section *** (OrderProduct CustomAttributes)

    // *** End programmer edit section *** (OrderProduct CustomAttributes)
    [AutoAltered()]
    [Caption("Товарная позиция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OrderProductE", new string[] {
            "Amount as \'Количество\'",
            "Product as \'Товар\'",
            "Product.Name as \'Товар\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("OrderProductE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class OrderProduct : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.NewProject.Product fProduct;
        
        private IIS.NewProject.Zakaz fZakaz;
        
        // *** Start programmer edit section *** (OrderProduct CustomMembers)

        // *** End programmer edit section *** (OrderProduct CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (OrderProduct.Amount CustomAttributes)

        // *** End programmer edit section *** (OrderProduct.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (OrderProduct.Amount Get start)

                // *** End programmer edit section *** (OrderProduct.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (OrderProduct.Amount Get end)

                // *** End programmer edit section *** (OrderProduct.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderProduct.Amount Set start)

                // *** End programmer edit section *** (OrderProduct.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (OrderProduct.Amount Set end)

                // *** End programmer edit section *** (OrderProduct.Amount Set end)
            }
        }
        
        /// <summary>
        /// Order product.
        /// </summary>
        // *** Start programmer edit section *** (OrderProduct.Product CustomAttributes)

        // *** End programmer edit section *** (OrderProduct.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        [NotNull()]
        public virtual IIS.NewProject.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (OrderProduct.Product Get start)

                // *** End programmer edit section *** (OrderProduct.Product Get start)
                IIS.NewProject.Product result = this.fProduct;
                // *** Start programmer edit section *** (OrderProduct.Product Get end)

                // *** End programmer edit section *** (OrderProduct.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderProduct.Product Set start)

                // *** End programmer edit section *** (OrderProduct.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (OrderProduct.Product Set end)

                // *** End programmer edit section *** (OrderProduct.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.NewProject.Zakaz.
        /// </summary>
        // *** Start programmer edit section *** (OrderProduct.Zakaz CustomAttributes)

        // *** End programmer edit section *** (OrderProduct.Zakaz CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Zakaz"})]
        public virtual IIS.NewProject.Zakaz Zakaz
        {
            get
            {
                // *** Start programmer edit section *** (OrderProduct.Zakaz Get start)

                // *** End programmer edit section *** (OrderProduct.Zakaz Get start)
                IIS.NewProject.Zakaz result = this.fZakaz;
                // *** Start programmer edit section *** (OrderProduct.Zakaz Get end)

                // *** End programmer edit section *** (OrderProduct.Zakaz Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderProduct.Zakaz Set start)

                // *** End programmer edit section *** (OrderProduct.Zakaz Set start)
                this.fZakaz = value;
                // *** Start programmer edit section *** (OrderProduct.Zakaz Set end)

                // *** End programmer edit section *** (OrderProduct.Zakaz Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OrderProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderProductE", typeof(IIS.NewProject.OrderProduct));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of OrderProduct.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfOrderProduct CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfOrderProduct CustomAttributes)
    public class DetailArrayOfOrderProduct : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.NewProject.DetailArrayOfOrderProduct members)

        // *** End programmer edit section *** (IIS.NewProject.DetailArrayOfOrderProduct members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type OrderProduct by index.
        /// </summary>
        /// <summary>
        /// Adds object with type OrderProduct.
        /// </summary>
        public DetailArrayOfOrderProduct(IIS.NewProject.Zakaz fZakaz) : 
                base(typeof(OrderProduct), ((ICSSoft.STORMNET.DataObject)(fZakaz)))
        {
        }
        
        public IIS.NewProject.OrderProduct this[int index]
        {
            get
            {
                return ((IIS.NewProject.OrderProduct)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.NewProject.OrderProduct dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
