//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.NewProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Zakaz.
    /// </summary>
    // *** Start programmer edit section *** (Zakaz CustomAttributes)

    // *** End programmer edit section *** (Zakaz CustomAttributes)
    [AutoAltered()]
    [Caption("Заказы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ZakazE", new string[] {
            "Status as \'Статус\'",
            "Coupon as \'Купон\'",
            "Coupon.ProductName as \'Купон\'",
            "Client as \'Клиент\'",
            "Client.Login as \'Клиент\'"}, Hidden=new string[] {
            "Coupon.ProductName",
            "Client.Login"})]
    [AssociatedDetailViewAttribute("ZakazE", "OrderProduct", "OrderProductE", true, "", "Товарная продукция", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ZakazE", "Coupon", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ProductName")]
    [MasterViewDefineAttribute("ZakazE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Login")]
    [View("ZakazL", new string[] {
            "Status as \'Статус\'",
            "Coupon.ProductName as \'Купон\'",
            "Client.Login as \'Клиент\'"})]
    public class Zakaz : ICSSoft.STORMNET.DataObject
    {
        
        private string fStatus;
        
        private IIS.NewProject.Coupon fCoupon;
        
        private IIS.NewProject.Client fClient;
        
        private IIS.NewProject.DetailArrayOfOrderProduct fOrderProduct;
        
        // *** Start programmer edit section *** (Zakaz CustomMembers)

        // *** End programmer edit section *** (Zakaz CustomMembers)

        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Zakaz.Status CustomAttributes)

        // *** End programmer edit section *** (Zakaz.Status CustomAttributes)
        [StrLen(255)]
        public virtual string Status
        {
            get
            {
                // *** Start programmer edit section *** (Zakaz.Status Get start)

                // *** End programmer edit section *** (Zakaz.Status Get start)
                string result = this.fStatus;
                // *** Start programmer edit section *** (Zakaz.Status Get end)

                // *** End programmer edit section *** (Zakaz.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zakaz.Status Set start)

                // *** End programmer edit section *** (Zakaz.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Zakaz.Status Set end)

                // *** End programmer edit section *** (Zakaz.Status Set end)
            }
        }
        
        /// <summary>
        /// Zakaz.
        /// </summary>
        // *** Start programmer edit section *** (Zakaz.Client CustomAttributes)

        // *** End programmer edit section *** (Zakaz.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        [NotNull()]
        public virtual IIS.NewProject.Client Client
        {
            get
            {
                // *** Start programmer edit section *** (Zakaz.Client Get start)

                // *** End programmer edit section *** (Zakaz.Client Get start)
                IIS.NewProject.Client result = this.fClient;
                // *** Start programmer edit section *** (Zakaz.Client Get end)

                // *** End programmer edit section *** (Zakaz.Client Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zakaz.Client Set start)

                // *** End programmer edit section *** (Zakaz.Client Set start)
                this.fClient = value;
                // *** Start programmer edit section *** (Zakaz.Client Set end)

                // *** End programmer edit section *** (Zakaz.Client Set end)
            }
        }
        
        /// <summary>
        /// Zakaz.
        /// </summary>
        // *** Start programmer edit section *** (Zakaz.Coupon CustomAttributes)

        // *** End programmer edit section *** (Zakaz.Coupon CustomAttributes)
        [PropertyStorage(new string[] {
                "Coupon"})]
        public virtual IIS.NewProject.Coupon Coupon
        {
            get
            {
                // *** Start programmer edit section *** (Zakaz.Coupon Get start)

                // *** End programmer edit section *** (Zakaz.Coupon Get start)
                IIS.NewProject.Coupon result = this.fCoupon;
                // *** Start programmer edit section *** (Zakaz.Coupon Get end)

                // *** End programmer edit section *** (Zakaz.Coupon Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zakaz.Coupon Set start)

                // *** End programmer edit section *** (Zakaz.Coupon Set start)
                this.fCoupon = value;
                // *** Start programmer edit section *** (Zakaz.Coupon Set end)

                // *** End programmer edit section *** (Zakaz.Coupon Set end)
            }
        }
        
        /// <summary>
        /// Zakaz.
        /// </summary>
        // *** Start programmer edit section *** (Zakaz.OrderProduct CustomAttributes)

        // *** End programmer edit section *** (Zakaz.OrderProduct CustomAttributes)
        public virtual IIS.NewProject.DetailArrayOfOrderProduct OrderProduct
        {
            get
            {
                // *** Start programmer edit section *** (Zakaz.OrderProduct Get start)

                // *** End programmer edit section *** (Zakaz.OrderProduct Get start)
                if ((this.fOrderProduct == null))
                {
                    this.fOrderProduct = new IIS.NewProject.DetailArrayOfOrderProduct(this);
                }
                IIS.NewProject.DetailArrayOfOrderProduct result = this.fOrderProduct;
                // *** Start programmer edit section *** (Zakaz.OrderProduct Get end)

                // *** End programmer edit section *** (Zakaz.OrderProduct Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zakaz.OrderProduct Set start)

                // *** End programmer edit section *** (Zakaz.OrderProduct Set start)
                this.fOrderProduct = value;
                // *** Start programmer edit section *** (Zakaz.OrderProduct Set end)

                // *** End programmer edit section *** (Zakaz.OrderProduct Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ZakazE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ZakazE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ZakazE", typeof(IIS.NewProject.Zakaz));
                }
            }
            
            /// <summary>
            /// "ZakazL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ZakazL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ZakazL", typeof(IIS.NewProject.Zakaz));
                }
            }
        }
    }
}
